// Regenerates src/lib/api-types.ts from the running FastAPI app's OpenAPI spec.
// Usage: npm run gen:types   (reads NEXT_PUBLIC_API_URL, default http://localhost:8000)
import { writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";

const base = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000").replace(/\/$/, "");
const url = new URL(`${base}/openapi.json`);

const ast = await openapiTS(url);
const header = `// Generated by \`npm run gen:types\` from ${url.pathname} of the Cinsight API. Do not edit by hand.\n\n`;
await writeFile(new URL("../src/lib/api-types.ts", import.meta.url), header + astToString(ast));
console.log(`Wrote src/lib/api-types.ts from ${url}`);
