// Generated by `npm run gen:types` from /openapi.json of the Cinsight API. Do not edit by hand.

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description One dashboard file. `name` is one of: kpis, outcomes, monthly, breakdowns, model_comparison, test_metrics, pr_curve, calibration, shap_importance, high_risk_top.
         */
        get: operations["dashboard_api_dashboard__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_api_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Batch
         * @description Send the CSV file itself as the request body (Content-Type: text/csv). It is read in memory and never written to disk.
         */
        post: operations["predict_batch_api_predict_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Complaints */
        get: operations["complaints_api_complaints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Complaints Export */
        get: operations["complaints_export_api_complaints_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sample-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sample Batch */
        get: operations["sample_batch_api_sample_batch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchResponse */
        BatchResponse: {
            /**
             * Columns
             * @description Original column order of the uploaded file
             */
            columns: string[];
            /** Rows */
            rows: components["schemas"]["BatchRow"][];
            summary: components["schemas"]["TierCounts"];
            /** Scored */
            scored: number;
            /** Rejected */
            rejected: number;
            /**
             * Rejected Rows
             * @description Row numbers skipped because every required column was blank
             */
            rejected_rows: number[];
        };
        /** BatchRow */
        BatchRow: {
            /**
             * Row
             * @description 1-based data row number in the uploaded file
             */
            row: number;
            /**
             * Values
             * @description Every original column of the row, as uploaded
             */
            values: {
                [key: string]: string;
            };
            /** Score */
            score: number;
            /**
             * Tier
             * @enum {string}
             */
            tier: "High" | "Medium" | "Low";
            /** Action */
            action: string;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /** Top Words */
            top_words: string[];
        };
        /** BreakdownRow */
        BreakdownRow: {
            /** Label */
            label: string;
            /** Complaints */
            complaints: number;
            /** Relief Rate */
            relief_rate: number;
        };
        /** Breakdowns */
        Breakdowns: {
            /** Overall Relief Rate */
            overall_relief_rate: number;
            /** Product */
            product: components["schemas"]["BreakdownRow"][];
            /** Issue */
            issue: components["schemas"]["BreakdownRow"][];
            /** Company */
            company: components["schemas"]["BreakdownRow"][];
            /** State */
            state: components["schemas"]["BreakdownRow"][];
            /** Tags */
            tags: components["schemas"]["BreakdownRow"][];
            /** Day Of Week */
            day_of_week: components["schemas"]["BreakdownRow"][];
        };
        /** Calibration */
        Calibration: {
            /** Split */
            split: string;
            /** Calibrated */
            calibrated: boolean;
            /** Note */
            note: string;
            /** Points */
            points: components["schemas"]["CalibrationPoint"][];
        };
        /** CalibrationPoint */
        CalibrationPoint: {
            /** Predicted */
            predicted: number;
            /** Observed */
            observed: number;
        };
        /** CompanyOption */
        CompanyOption: {
            /** Name */
            name: string;
            /** Complaints */
            complaints: number;
        };
        /**
         * ComplaintInput
         * @description One complaint, keyed by the columns in model_meta.json -> required_input_columns.
         *
         *     Every key must be present; a value may be null or empty (it is then treated as missing).
         * @example {
         *       "Company": "CITIBANK, N.A.",
         *       "Consumer complaint narrative": "I was charged twice for the same purchase and the bank refused a refund.",
         *       "Date received": "2025-12-15",
         *       "Issue": "Problem with a purchase shown on your statement",
         *       "Product": "Credit card",
         *       "State": "NY",
         *       "Sub-issue": "Not provided",
         *       "Sub-product": "General-purpose credit card or charge card",
         *       "Tags": "Not provided"
         *     }
         */
        ComplaintInput: {
            /**
             * Date Received
             * @description YYYY-MM-DD
             */
            "Date received": string | null;
            /** Consumer Complaint Narrative */
            "Consumer complaint narrative": string | null;
            /** Product */
            Product: string | null;
            /** Sub-Product */
            "Sub-product": string | null;
            /** Issue */
            Issue: string | null;
            /** Sub-Issue */
            "Sub-issue": string | null;
            /** Company */
            Company: string | null;
            /** State */
            State: string | null;
            /** Tags */
            Tags: string | null;
        };
        /** ComplaintPage */
        ComplaintPage: {
            /** Items */
            items: components["schemas"]["ScoredComplaint"][];
            /**
             * Total
             * @description Rows matching every filter
             */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** @description Rows per tier matching every filter except tier */
            tier_counts: components["schemas"]["TierCounts"];
        };
        /** Confusion */
        Confusion: {
            /** Tn */
            tn: number;
            /** Fp */
            fp: number;
            /** Fn */
            fn: number;
            /** Tp */
            tp: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Message */
            message: string;
            /**
             * Missing Columns
             * @default []
             */
            missing_columns: string[];
        };
        /** ErrorResponse */
        ErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /** FormOptions */
        FormOptions: {
            /**
             * Hierarchy
             * @description Product -> Sub-product -> Issue -> list of Sub-issues
             */
            hierarchy: {
                [key: string]: {
                    [key: string]: {
                        [key: string]: string[];
                    };
                };
            };
            /** Companies */
            companies: components["schemas"]["CompanyOption"][];
            /** States */
            states: string[];
            /** Tags */
            tags: string[];
            /** Missing Label */
            missing_label: string;
            /** Required Input Columns */
            required_input_columns: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Model Name */
            model_name: string;
            /** Calibrated */
            calibrated: boolean;
            /** Versions */
            versions: {
                [key: string]: string;
            };
            /** Created At */
            created_at: string;
        };
        /** Kpis */
        Kpis: {
            /** Total Complaints */
            total_complaints: number;
            /** Labeled Complaints */
            labeled_complaints: number;
            /** Unlabeled Complaints */
            unlabeled_complaints: number;
            /** Relief Count */
            relief_count: number;
            /** Relief Rate */
            relief_rate: number;
            /** Date From */
            date_from: string;
            /** Date To */
            date_to: string;
            /** Test Month */
            test_month: string;
            /** Test Complaints */
            test_complaints: number;
            test_tier_counts: components["schemas"]["TierCounts"];
            test_tier_shares: components["schemas"]["TierShares"];
            /** Pr Auc Test */
            pr_auc_test: number;
            /** Pr Auc Baseline */
            pr_auc_baseline: number;
        };
        /** ModelComparison */
        ModelComparison: {
            /** Split */
            split: string;
            /** Metric Note */
            metric_note: string;
            /** Positive Rate */
            positive_rate: number;
            /** Models */
            models: components["schemas"]["ModelScore"][];
        };
        /** ModelMeta */
        ModelMeta: {
            /** Model Name */
            model_name: string;
            /** Calibrated */
            calibrated: boolean;
            /** Score Label */
            score_label: string;
            /** Score Meaning */
            score_meaning: string;
            /** Trained On */
            trained_on: string;
            /** Threshold Tuned On */
            threshold_tuned_on: string;
            /** Tested On */
            tested_on: string;
            /** Features */
            features: string[];
            /** Required Input Columns */
            required_input_columns: string[];
            thresholds: components["schemas"]["Thresholds"];
            /** Tiers */
            tiers: components["schemas"]["TierRule"][];
            /** Base Rate Train */
            base_rate_train: number;
            /** Versions */
            versions: {
                [key: string]: string;
            };
            /** Created At */
            created_at: string;
        };
        /** ModelScore */
        ModelScore: {
            /** Model */
            model: string;
            /** Pr Auc */
            pr_auc: number;
            /** F1 At 0 5 */
            f1_at_0_5: number;
            /** Precision At 0 5 */
            precision_at_0_5: number;
            /** Recall At 0 5 */
            recall_at_0_5: number;
        };
        /** MonthlyPoint */
        MonthlyPoint: {
            /** Month */
            month: string;
            /** Complaints */
            complaints: number;
            /** Relief Rate */
            relief_rate: number;
            /** Split */
            split: string;
            /** Predicted High Share */
            predicted_high_share: number | null;
        };
        /** Outcome */
        Outcome: {
            /** Outcome */
            outcome: string;
            /** Count */
            count: number;
            /** Share */
            share: number;
            /**
             * Relief
             * @enum {integer}
             */
            relief: 0 | 1;
        };
        /** PrCurve */
        PrCurve: {
            /** High Threshold */
            high_threshold: number;
            /** Validation */
            validation: components["schemas"]["PrPoint"][];
            /** Test */
            test: components["schemas"]["PrPoint"][];
        };
        /** PrPoint */
        PrPoint: {
            /** Threshold */
            threshold: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
        };
        /** PredictResponse */
        PredictResponse: {
            /** Score */
            score: number;
            /**
             * Tier
             * @enum {string}
             */
            tier: "High" | "Medium" | "Low";
            /** Action */
            action: string;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /** Top Words */
            top_words: string[];
            /** @description Null when the band has too few complaints to be reliable */
            similar: components["schemas"]["SimilarComplaints"] | null;
        };
        /** Reason */
        Reason: {
            /** Factor */
            factor: string;
            /**
             * Contribution
             * @description Contribution to the log-odds of relief
             */
            contribution: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "toward relief" | "away from relief";
        };
        /**
         * ScoredComplaint
         * @description One scored December complaint (high_risk_top.json and test_scored.parquet rows).
         */
        ScoredComplaint: {
            /** Complaint Id */
            "Complaint ID": number;
            /** Date Received */
            "Date received": string;
            /** Product */
            Product: string;
            /** Sub-Product */
            "Sub-product": string;
            /** Issue */
            Issue: string;
            /** Sub-Issue */
            "Sub-issue": string;
            /** Company */
            Company: string;
            /** State */
            State: string;
            /** Tags */
            Tags: string;
            /** Score */
            score: number;
            /**
             * Tier
             * @enum {string}
             */
            tier: "High" | "Medium" | "Low";
            /** Action */
            action: string;
            /**
             * Narrative Preview
             * @description First 280 characters of the narrative
             */
            narrative_preview: string;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /** Top Words */
            top_words: string[];
            /** Top Reason */
            top_reason: string | null;
        };
        /** ShapFeature */
        ShapFeature: {
            /** Feature */
            feature: string;
            /** Group */
            group: string;
            /** Mean Abs Shap */
            mean_abs_shap: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "toward relief" | "away from relief";
        };
        /** ShapGroup */
        ShapGroup: {
            /** Group */
            group: string;
            /** Mean Abs Shap */
            mean_abs_shap: number;
            /** Share */
            share: number;
        };
        /** ShapImportance */
        ShapImportance: {
            /** Method */
            method: string;
            /** By Group */
            by_group: components["schemas"]["ShapGroup"][];
            /** Top Features */
            top_features: components["schemas"]["ShapFeature"][];
        };
        /**
         * SimilarComplaints
         * @description Observed relief rate among complaints that scored in the same band (score_bands.json).
         */
        SimilarComplaints: {
            /** Score From */
            score_from: number;
            /** Score To */
            score_to: number;
            /** Complaints */
            complaints: number;
            /** Relief Rate */
            relief_rate: number;
            /** Split */
            split: string;
        };
        /** TestMetrics */
        TestMetrics: {
            /** Split */
            split: string;
            /** N */
            n: number;
            /** Positive Rate */
            positive_rate: number;
            /** Threshold */
            threshold: number;
            /** Pr Auc */
            pr_auc: number;
            /** Baseline Pr Auc */
            baseline_pr_auc: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** F1 */
            f1: number;
            /** Accuracy */
            accuracy: number;
            confusion: components["schemas"]["Confusion"];
            tier_counts: components["schemas"]["TierCounts"];
            validation: components["schemas"]["ValidationMetrics"];
        };
        /** Thresholds */
        Thresholds: {
            /** High */
            high: number;
            /** Medium */
            medium: number;
        };
        /** TierCounts */
        TierCounts: {
            /** High */
            High: number;
            /** Medium */
            Medium: number;
            /** Low */
            Low: number;
        };
        /** TierRule */
        TierRule: {
            /**
             * Tier
             * @enum {string}
             */
            tier: "High" | "Medium" | "Low";
            /** Rule */
            rule: string;
            /** Action */
            action: string;
        };
        /** TierShares */
        TierShares: {
            /** High */
            High: number;
            /** Medium */
            Medium: number;
            /** Low */
            Low: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationMetrics */
        ValidationMetrics: {
            /** Pr Auc */
            pr_auc: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** F1 */
            f1: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelMeta"];
                };
            };
        };
    };
    options_api_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormOptions"];
                };
            };
        };
    };
    dashboard_api_dashboard__name__get: {
        parameters: {
            query?: {
                /** @description List files only: first N items */
                limit?: number | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Kpis"] | components["schemas"]["Outcome"][] | components["schemas"]["MonthlyPoint"][] | components["schemas"]["Breakdowns"] | components["schemas"]["ModelComparison"] | components["schemas"]["TestMetrics"] | components["schemas"]["PrCurve"] | components["schemas"]["Calibration"] | components["schemas"]["ShapImportance"] | components["schemas"]["ScoredComplaint"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_api_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_batch_api_predict_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    complaints_api_complaints_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                tier?: ("High" | "Medium" | "Low") | null;
                product?: string | null;
                company?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                /** @description Complaint ID, company or words in the narrative */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complaints_export_api_complaints_export_get: {
        parameters: {
            query?: {
                tier?: ("High" | "Medium" | "Low") | null;
                product?: string | null;
                company?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                /** @description Complaint ID, company or words in the narrative */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Streamed CSV, same filters as /api/complaints */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_batch_api_sample_batch_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description sample_batch.csv */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
        };
    };
}
